[build-system]
requires = [
    "setuptools>=61.2",
    "wheel",
]

[project]
name = "owo"
version = "0.1.0"
description = "OwO"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "selenium",
]
